sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
cache:
  directories:
    - '$HOME/.m2/repository'
install:
  - mvn --version
script:
  - mvn install -e -B -Dstrict
  - rm -rf $HOME/.m2/repository/com/opengamma/analytics
  - rm -rf $HOME/.m2/repository/com/opengamma/strata
